name: Add latest tag to new release
on:
  release:
    types: [published]

jobs:
  # tag:
  #   name: Add/update tag to new release
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Run latest-tag
  #       uses: EndBug/latest-tag@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs:
    name: Documentation
    runs-on: ubuntu-18.04
    needs: tag
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build and deploy documentation
        uses: dbots-pkg/action-docs@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
